Data:
  # Basics
  log_dir: '/data/lightSpec/logs'
  exp_num: 1
  light_model_name: "CNNEncoder"
  spec_model_name: "CNNEncoderDecoder"
  # Data
  dataset: "LightSpecDataset"
  data_dir: '/data/lightPred/data'
  spectra_dir: '/data/lamost/data'
  batch_size: 64
  num_epochs: 1000
  max_len_spectra: 4096
  max_days_lc: 720
  lc_freq: 0.0208
  meta_columns: ['Teff', 'Mstar']
  test_run: False
  create_umap: False
  load_checkpoint: True
  checkpoint_path: '/data/lightSpec/logs/lightspec_2024-12-17/lightspec_1.pth'

Astroconformer:
  # Model
  in_channels: 1
  encoder: ["mhsa_pro", "conv", "mhsa_pro"]
  decoder: ["mhsa_decoder",  "conv", "mhsa_decoder"]
  timeshift: false
  num_layers: 8
  num_decoder_layers: 12
  stride: 2
  encoder_dim: 128
  decoder_dim: 512
  num_heads: 4
  kernel_size: 3
  dropout_p: 0.3
  output_dim: 3
  norm: "postnorm"
  beta: 1
  load_light_checkpoint: True
  light_checkpoint_path: '/data/lightSpec/logs/exp5/astroconf_lc_1.pth'

AstroEncoderDecoder:
  # Model
  in_channels: 1
  encoder: ["mhsa_pro", "conv", "mhsa_pro"]
  decoder: ["mhsa_decoder",  "conv", "mhsa_decoder"]
  timeshift: false
  num_layers: 6
  num_decoder_layers: 6
  stride: 2
  encoder_dim: 512
  decoder_dim: 512
  num_heads: 4
  kernel_size: 3
  dropout_p: 0.2
  output_dim: 3
  norm: "postnorm"
  load_spec_checkpoint: False
  spec_checkpoint_path: '/data/lightSpec/logs/exp6/astroconf_spectra_3.pth'

CNNEncoder:
  # Model
  in_channels: 1
  num_layers: 8
  stride: 1
  encoder_dims: [32,64,128,256,512]
  kernel_size: 3
  dropout_p: 0.2
  output_dim: 2
  beta: 1
  load_checkpoint: True
  avg_output: True
  checkpoint_num: 2
  activation: "sine"
  sine_w0: 1.0
  load_checkpoint: True
  checkpoint_path: '/data/lightSpec/logs/light_2024-11-27/CNNEncoder_lc_1.pth'

CNNEncoderDecoder:
  # Model
  in_channels: 1
  num_layers: 4
  stride: 1
  encoder_dims: [32,64,128,256,512]
  transformer_layers: 4
  kernel_size: 3
  dropout_p: 0.3
  avg_output: True
  output_dim: 2
  beta: 1
  load_checkpoint: True
  checkpoint_path: '/data/lightSpec/logs/spec_2024-12-12/CNNEncoderDecoder_spectra_2.pth'
  checkpoint_num: 2
  activation: "silu"

MoCo:
  # Model
  K: 4096
  m: 0.9
  T: 0.05
  hidden_dim: 1024
  projection_dim: 32
  num_layers: 6
  freeze_lightcurve: False
  freeze_spectra: False
  bidirectional: True
  transformer: True

AdversarialAlignment:
  # Model
  shared_dim: 64   
  gen_dims: [1024, 128, 64]  
  disc_dims: [64, 128, 1024]

SimSiam:
  # Model
  input_dim: 512
  hidden_dim: 64
  projection_dim: 32
  output_dim: 32
  dropout: 0.2
  freeze_backbone: False

CNNBackbone:
  # Model
  in_channels: 1
  num_layers: 8
  stride: 1
  encoder_dims: [64,128,256,512]
  kernel_size: 3
  dropout_p: 0.3
  beta: 1
  avg_output: True
  activation: "silu"
  sine_w0: 1.0
  load_checkpoint: False

conv_args:
  in_channels: 1
  num_layers: 8
  stride: 1
  encoder_dims: [64,128,256,512]
  kernel_size: 3
  dropout_p: 0.3
  beta: 1
  avg_output: True
  activation: "silu"
  
Optimization SSL:
  # Optimization
  max_lr:  1e-4
  weight_decay: 5e-5
  warmup_pct: 0.15
  steps_per_epoch: 3500
  momentum: 0.85
  nesterov: true
  optimizer: "sgd"

Optimization:
  # Optimization
  max_lr: 1e-5
  weight_decay: 5e-6
  warmup_pct: 0.3
  steps_per_epoch: 3500