Data:
  # Basics
  log_dir: '/data/lightSpec/logs'
  # Data
  dataset: "KeplerDataset"
  data_dir: '/data/lightPred/data'
  model_name: "MultiEncoder"
  batch_size: 16
  num_epochs: 1000
  exp_num: 3
  max_len_spectra: 4096
  max_days_lc: 270
  max_len_lc: 26112
  lc_freq: 0.0208
  create_umap: False
  masked_transform: False
  use_acf: True
  scale_flux: True
  ssl_weight: 0
  labels: ['Prot']


Conformer:
  encoder: ["mhsa_pro", "conv", "ffn"]
  timeshift: false
  num_layers: 6
  stride: 2
  encoder_dim: 256
  num_heads: 8
  kernel_size: 3
  dropout_p: 0.2
  norm: "shortcut"

MultiTaskRegressor:
  in_channels: 2
  num_layers: 8
  stride: 1
  encoder_dims: [32,64,128,256,512, 2048]
  transformer_layers: 4
  kernel_size: 3
  dropout_p: 0.2
  avg_output: True
  output_dim: 4
  num_quantiles: 5
  beta: 1
  load_checkpoint: False
  checkpoint_num: 1
  activation: "sine"
  sine_w0: 1.0
  checkpoint_path: '/data/lightSpec/logs/light_2025-03-03/MultiTaskRegressor_lc_2.pth'

MultiTaskSimSiam:
  # Model
  backbone: "cnn"
  in_channels: 1
  num_layers: 8
  stride: 1
  encoder_dims: [32,64,128,256,512, 2048]
  kernel_size: 3
  dropout_p: 0.1
  output_dim: 1
  beta: 1
  avg_output: True
  load_checkpoint: False
  checkpoint_num: 1
  activation: "sine"
  sine_w0: 1.0
  checkpoint_path: '/data/lightSpec/logs/light_2025-03-03/MultiEncoder_lc_2.pth'

MultiEncoder:
  # Model
  backbone: "cnn"
  in_channels: 3
  num_layers: 4
  stride: 1
  encoder_dims: [32,64,128,256]
  kernel_size: 3
  dropout_p: 0.1
  output_dim: 2
  beta: 1
  avg_output: False
  load_checkpoint: False
  checkpoint_num: 1
  activation: "silu"
  sine_w0: 1.0
  checkpoint_path: '/data/lightSpec/logs/light_2025-03-12//MultiTaskSimSiam_lc_1.pth'

Regressor:
  encoder_dim: 256
  output_dim: 2
  num_quantiles: 5
  activation: "sine"
  sine_w0: 2.0

CNNEncoder:
  # Model
  in_channels: 3
  num_layers: 8
  stride: 1
  encoder_dims: [32,64,128,256,512]
  kernel_size: 3
  dropout_p: 0.3
  output_dim: 2
  beta: 1
  load_checkpoint: False
  checkpoint_num: 1
  activation: "sine"
  sine_w0: 1.0
  avg_output: True
  checkpoint_path: '/data/lightSpec/logs/light_2024-11-27/CNNEncoder_lc_1.pth'

CNNRegressor:
  activation: sine
  avg_output: true
  beta: 1
  checkpoint_num: 1
  dropout_p: 0.3
  encoder_dims: [32,64,128,256,512,2048]
  num_layers: 8
  num_quantiles: 5
  output_dim: 2
  sine_w0: 1.0
  stride: 1
  load_checkpoint: True
  checkpoint_path: '/data/lightSpec/logs/light_2025-01-05/CNNRegressor_lc_decode_1.pth'

CNNEncoderDecoder:
  # Model
  in_channels: 1
  num_layers: 8
  stride: 1
  encoder_dims: [32,64,128,256,512]
  kernel_size: 3
  dropout_p: 0.3
  output_dim: 2
  beta: 1
  load_checkpoint: False
  checkpoint_num: 1
  activation: "sine"
  sine_w0: 1.0
  avg_output: False
  checkpoint_path: '/data/lightSpec/logs/light_2025-02-02/CNNEncoderDecoder_lc_2.pth'


AstroConformer:
  # Model
  in_channels: 1
  encoder: ["mhsa_pro", "conv", "mhsa_pro"]
  timeshift: false
  num_layers: 6
  num_decoder_layers: 6
  stride: 20
  encoder_dim: 512
  decoder_dim: 512
  num_heads: 4
  kernel_size: 3
  dropout_p: 0.2
  output_dim: 3
  norm: "postnorm"
  load_spec_checkpoint: False
  spec_checkpoint_path: '/data/lightSpec/logs/exp6/astroconf_spectra_3.pth'



Optimization:
  # Optimization
  max_lr: 1e-4
  weight_decay: 1e-5
  warmup_pct: 0.15
  steps_per_epoch: 2500
  quantiles: [0.1,0.25,0.5,0.75,0.9]
  sb_weight: 0.1
  energy_weight: 0

