Data:
  # Basics
  log_dir: '/data/lightSpec/logs'
  # Data
  dataset: "KeplerDataset"
  data_dir: '/data/lightPred/data'
  light_model_name: "DoubleInputRegressor"
  spec_model_name: "MultiTaskRegressor"
  batch_size: 16
  num_epochs: 1000
  exp_num: test_prot
  max_len_spectra: 4096
  max_days_lc: 270
  max_len_lc: 34560
  lc_freq: 0.0208
  create_umap: False
  load_checkpoint: False
  masked_transform: False
  use_acf: True
  use_fft: True
  scale_flux: False
  ssl_weight: 0
  in_channels: 3
  meta_columns: []
  labels: ['Prot']
  checkpoint_path: '/data/lightSpec/logs/light_2025-03-19/DoubleInputRegressor_lc_3_ssl.pth'

DoubleInputRegressor_lc:
  encoder_only: True
  stacked_input: True
  load_checkpoint: True
  output_dim: 1
  num_quantiles: 1
  dropout_p: 0.3  
  checkpoint_path: '/data/lightSpec/logs/light_2025-03-19/DoubleInputRegressor_lc_3_ssl.pth'



MultiEncoder_lc:
  # Model
  backbone: 'cnn'
  in_channels: 3
  num_layers: 8
  stride: 1
  encoder_dims: [32,64,128,256,512,1024]
  kernel_size: 3
  dropout_p: 0.1
  output_dim: 4 
  beta: 1
  avg_output: True
  load_checkpoint: False
  checkpoint_num: 1
  activation: "sine"
  sine_w0: 1.0
  checkpoint_path: '/data/lightSpec/logs/light_2025-03-03/MultiEncoder_lc_2.pth'


CNNEncoder_lc:
  # Model
  in_channels: 2
  num_layers: 6
  stride: 1
  encoder_dims: [32,64,128,256,512]
  kernel_size: 3
  dropout_p: 0.3
  output_dim: 2
  beta: 1
  load_checkpoint: False
  checkpoint_num: 1
  activation: "sine"
  sine_w0: 1.0
  avg_output: True
  checkpoint_path: '/data/lightSpec/logs/light_2024-11-27/CNNEncoder_lc_1.pth'

CNNRegressor_lc:
  activation: sine
  avg_output: true
  beta: 1
  checkpoint_num: 1
  dropout_p: 0.3
  encoder_dims: [32,64,128,256,512,2048]
  num_layers: 8
  num_quantiles: 5
  output_dim: 2
  sine_w0: 1.0
  stride: 1
  load_checkpoint: True
  checkpoint_path: '/data/lightSpec/logs/light_2025-01-05/CNNRegressor_lc_decode_1.pth'

CNNEncoderDecoder_lc:
  # Model
  in_channels: 1
  num_layers: 8
  stride: 1
  encoder_dims: [32,64,128,256,512]
  kernel_size: 3
  dropout_p: 0.3
  output_dim: 2
  beta: 1
  load_checkpoint: False
  checkpoint_num: 1
  activation: "sine"
  sine_w0: 1.0
  avg_output: False
  checkpoint_path: '/data/lightSpec/logs/light_2025-02-02/CNNEncoderDecoder_lc_2.pth'


AstroConformer_lc:
  # Model
  in_channels: 2
  encoder: ["mhsa_pro", "conv"]
  timeshift: false
  num_layers: 5
  num_decoder_layers: 6
  stride: 20
  encoder_dim: 512
  decoder_dim: 128
  num_heads: 8
  kernel_size: 3
  dropout_p: 0.3
  output_dim: 3
  encoder_only: True
  norm: "postnorm"
  load_checkpoint: False
  spec_checkpoint_path: '/data/lightSpec/logs/exp6/astroconf_spectra_3.pth'



Optimization SSL:
  # Optimization
  max_lr: 5e-5
  weight_decay: 1e-5
  warmup_pct: 0.15
  steps_per_epoch: 2500
  quantiles: [0.1, 0.25, 0.5, 0.75, 0.9]

Optimization:
  # Optimization
  max_lr: 1e-5
  weight_decay: 5e-6
  warmup_pct: 0.3
  steps_per_epoch: 3500
