Data:
  # Basics
  log_dir: '/data/lightSpec/logs'
  exp_num: 7
  light_model_name: "CNNEncoder"
  spec_model_name: "AstroEncoderDecoder"
  # Data
  dataset: "KeplerDataset"
  data_dir: '/data/lightPred/data'
  spectra_dir: '/data/lamost/data'
  batch_size: 8
  num_epochs: 20
  max_len_spectra: 3909
  max_days_lc: 720
  lc_freq: 0.0208

Astroconformer:
  # Model
  in_channels: 1
  encoder: ["mhsa_pro", "conv", "mhsa_pro"]
  decoder: ["mhsa_decoder",  "conv", "mhsa_decoder"]
  timeshift: false
  num_layers: 12
  num_decoder_layers: 12
  stride: 16
  encoder_dim: 512
  decoder_dim: 512
  num_heads: 4
  kernel_size: 3
  dropout_p: 0.3
  output_dim: 3
  norm: "postnorm"
  beta: 1
  load_light_checkpoint: True
  light_checkpoint_path: '/data/lightSpec/logs/exp5/astroconf_lc_1.pth'

AstroEncoderDecoder:
  # Model
  in_channels: 1
  encoder: ["mhsa_pro", "conv", "mhsa_pro"]
  decoder: ["mhsa_decoder",  "conv", "mhsa_decoder"]
  timeshift: false
  num_layers: 6
  num_decoder_layers: 6
  stride: 2
  encoder_dim: 512
  decoder_dim: 512
  num_heads: 4
  kernel_size: 3
  dropout_p: 0.2
  output_dim: 3
  norm: "postnorm"
  load_spec_checkpoint: False
  spec_checkpoint_path: '/data/lightSpec/logs/exp6/astroconf_spectra_3.pth'


CNNEncoder:
  # Model
  in_channels: 1
  num_layers: 6
  stride: 1
  encoder_dims: [64,128,256,512]
  kernel_size: 3
  dropout_p: 0.2
  output_dim: 2
  beta: 1
  load_checkpoint: True
  checkpoint_num: 2
  activation: "sine"
  sine_w0: 1.0
  load_light_checkpoint: False
  light_checkpoint_path: '/data/lightSpec/logs/exp9/CNNEncoder_lc_2.pth'

MoCo:
  # Model
  K: 2048
  m: 0.99
  T: 0.1
  hidden_dim: 512
  projection_dim: 512
  bidirectional: False

SimSiam:
  # Model
  input_dim: 512
  hidden_dim: 256
  projection_dim: 128
  output_dim: 128
  dropout: 0.2
  

Optimization SSL:
  # Optimization
  max_lr: 1e-5
  weight_decay: 1e-5
  warmup_pct: 0.15
  steps_per_epoch: 3500

Optimization:
  # Optimization
  max_lr: 1e-5
  weight_decay: 5e-6
  warmup_pct: 0.3
  steps_per_epoch: 3500