Data:
  # Basics
  log_dir: '/data/lightSpec/logs'
  # Data
  dataset: "SpectraDataset"
  data_dir: '/data/lamost/data'
  model_name: CNNEncoderDecoder
  batch_size: 4
  num_epochs: 20
  exp_num: 8
  max_len_spectra: 3520
  max_days_lc: 720
  lc_freq: 0.0208

AstroEncoderDecoder:
  # Model
  in_channels: 1
  encoder: ["mhsa_pro", "conv", "mhsa_pro"]
  decoder: ["mhsa_decoder",  "conv", "mhsa_decoder"]
  timeshift: false
  num_layers: 4
  num_decoder_layers: 4
  stride: 2
  encoder_dim: 256
  decoder_dim: 256
  num_heads: 4
  kernel_size: 3
  dropout_p: 0.35
  output_dim: 3
  norm: "postnorm"
  load_checkpoint: False
  checkpoint_path: '/data/lightSpec/logs/exp6/astroconf_spectra.pth'
  checkpoint_num: 1
  beta: 1

CNNEncoderDecoder:
  # Model
  in_channels: 1
  num_layers: 6
  stride: 1
  encoder_dims: [32,64,128,256,512]
  kernel_size: 3
  dropout_p: 0.3
  avg_output: False
  output_dim: 2
  beta: 1
  load_checkpoint: False
  checkpoint_num: 1
  activation: "silu"

Optimization SSL:
  # Optimization
  max_lr: 1e-5
  weight_decay: 1e-5
  warmup_pct: 0.3
  steps_per_epoch: 3500

Optimization:
  # Optimization
  max_lr: 1e-5
  weight_decay: 5e-6
  warmup_pct: 0.3
  steps_per_epoch: 3500