Data:
  # Basics
  log_dir: '/data/lightSpec/logs'
  exp_num: 1
  model_name: "MultiTaskRegressor"
  # Data
  dataset: "LightSpecDatasetV2"
  data_dir: '/data/lightPred/data'
  spectra_dir: '/data/lamost/data'
  batch_size: 64
  num_epochs: 1000
  max_len_spectra: 4096
  max_days_lc: 270
  max_len_lc: 13056
  lc_freq: 0.0208
  continuum_norm: True
  meta_columns: ['Teff', 'Mstar']
  test_run: False
  create_umap: False
  load_checkpoint: False
  masked_transform: False
  use_acf: True
  combined_embed: True
  pred_coeff_val: None
  checkpoint_path: ''

AstroEncoderDecoder:
  # Model
  in_channels: 1
  encoder: ["mhsa_pro", "conv", "mhsa_pro"]
  decoder: ["mhsa_decoder",  "conv", "mhsa_decoder"]
  timeshift: false
  num_layers: 6
  num_decoder_layers: 6
  stride: 2
  encoder_dim: 512
  decoder_dim: 512
  num_heads: 4
  kernel_size: 3
  dropout_p: 0.2
  output_dim: 3
  norm: "postnorm"
  load_spec_checkpoint: False
  spec_checkpoint_path: '/data/lightSpec/logs/exp6/astroconf_spectra_3.pth'


MultiTaskRegressor:
  in_channels: 1
  num_layers: 5
  stride: 1
  encoder_dims: [64,128,256,1024,2048]
  transformer_layers: 4
  kernel_size: 3
  dropout_p: 0.2
  avg_output: True
  output_dim: 3
  num_quantiles: 5
  beta: 1
  load_checkpoint: False
  checkpoint_num: 1
  activation: "silu"
  checkpoint_path: "/data/lightSpec/logs/spec_decode2_2025-02-16/MultiTaskRegressor_spectra_decode_4.pth"


Conformer:
  encoder: ["mhsa_pro", "conv", "ffn"]
  timeshift: false
  num_layers: 8
  encoder_dim: 2048
  num_heads: 8
  kernel_size: 3
  dropout_p: 0.2
  norm: "postnorm"


Transformer:
  in_channels: 1
  num_layers: 4
  encoder_dim: 256
  dropout_p: 0.2
  num_heads: 8
  dropout: 0.0
  output_dim: 64
  num_quantiles: 1
  checkpoint_num: 1
  load_checkpoint: False

CNNEncoderDecoder_lc:
  # Model
  in_channels: 1
  num_layers: 8
  stride: 1
  encoder_dims: [32,64,128,256,512]
  kernel_size: 3
  dropout_p: 0.3
  output_dim: 2
  beta: 1
  load_checkpoint: True
  checkpoint_num: 1
  activation: "sine"
  sine_w0: 1.0
  avg_output: True
  checkpoint_path: '/data/lightSpec/logs/light_2025-02-04/CNNEncoderDecoder_lc_2.pth'

predictor:
  in_dim: 64
  hidden_dim: 256
  out_dim: 64
  w_dim: 2
 
Optimization SSL:
  # Optimization
  max_lr:  5e-5
  weight_decay: 1e-6
  warmup_pct: 0.15
  steps_per_epoch: 3500
  momentum: 0.95
  nesterov: true
  optimizer: "adamw"

Optimization:
  # Optimization
  max_lr: 1e-5
  weight_decay: 5e-6
  warmup_pct: 0.3
  steps_per_epoch: 3500

